### ISSUE TITLE
Remove space in --include flag in curl request

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/rails-api#17]
Currently -- include 
- @J-Weeks

**Comment by berziiii** [comment]
Corrected in 58092ce7d2a53b34cd7937a19e6bbb2b1fd04172. @J-Weeks  can we close?

**Comment by berziiii** [comment]
@J-Weeks okay to close?

**Comment by raq929** [comment]
This issue seems resolved.
