### ISSUE TITLE
Clarity needed between lesson and diagnostic associated with lesson

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/rails-api#19]
To my understanding, the focus of the rails-api lesson is to discuss Rails at a very high level and to execute the correct commands to create a new rails-api, with little to no explanation of what the commands are actually doing. 

Due to this, the diagnostic has questions that are more specific than what is covered during the lesson itself. Therefore attention should be given to either providing more explanation in the lesson itself of the commands, actions, scaffolding, serializers, etc. or several questions on the rails-api diagnostic should be adjusted to be at a higher level of check for understanding to match what the lesson provides.

**Comment by raq929** [comment]
I vote for option B, high level check for understanding.
The rails-api-single diagnostic can be the check for knowledge of commands.

**Comment by jrhorn424** [comment]
>  several questions on the rails-api diagnostic should be adjusted to be at a higher level of check for understanding to match what the lesson provides

This.

**Comment by jrhorn424** [comment]
Closing to track over in `rails-api-diagnostic`. https://github.com/ga-wdi-boston/rails-api-diagnostic/issues/83
