### ISSUE TITLE
Rails app accidentally committed?

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/rails-api#23]
It looks like previous versions of this repo (I'm looking at 95d10a924a6afeef4d661f680436b755c011744d) did not have the full rails app, which makes sense, since we are supposed to make one.

Was committing the rails app an accident, or is there something I'm missing here?
As it is, I can't run the commands specified in the repo because the app already exists.

**Comment by raq929** [comment]
From slack:
@gaand What makes more sense to you, scaffolding from the template or generating an app?  Pick the one you think is correct and go with that making adjustments as necessary.  If you want more direction, then go with the template and reference the generate command but don't use them, "If you were starting from scratch... But we've provided this scaffolding." or some such.

[3:30 PM]  
Rachel Stevens  For rails-api, generating an app. They'll have three examples of scaffolding from template the next day. Plus changing to scaffolding from template would require a lot of README updates that I don't have time to do carefully.

**Comment by raq929** [comment]
Aaaand I changed my mind about this. Generating a rails app from scratch led to multiple problems with spring and the rails-api gem.

**Comment by jrhorn424** [comment]
I'd rather not `rails new` either. I'll be updating from `rails-template`.

I believe this can be closed as the original question has been answered?
