### ISSUE TITLE
Remove TODOs at bottom of README

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/rails-api#33]
```diff
- <!-- TODO -   `rake nag` checks your code style. -->
- <!-- TODO -   `rake lint` checks your code for syntax errors. -->
```

These are out-of-date have been covered by the steps listed above them.

**Comment by jrhorn424** [comment]
Ah, but they have not. See https://github.com/ga-wdi-boston/rails-api-template/issues/35
